// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pCommentContentFieldNames          = builder.RawFieldNames(&PCommentContent{})
	pCommentContentRows                = strings.Join(pCommentContentFieldNames, ",")
	pCommentContentRowsExpectAutoSet   = strings.Join(stringx.Remove(pCommentContentFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	pCommentContentRowsWithPlaceHolder = strings.Join(stringx.Remove(pCommentContentFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	pCommentContentModel interface {
		Insert(ctx context.Context, data *PCommentContent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PCommentContent, error)
		Update(ctx context.Context, data *PCommentContent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPCommentContentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PCommentContent struct {
		Id         int64  `db:"id"`          // 内容ID
		CommentId  int64  `db:"comment_id"`  // 评论ID
		UserId     int64  `db:"user_id"`     // 用户ID
		Content    string `db:"content"`     // 内容
		Type       int64  `db:"type"`        // 类型，1标题，2文字段落，3图片地址，4视频地址，5语音地址，6链接地址
		Sort       int64  `db:"sort"`        // 排序，越小越靠前
		CreatedOn  int64  `db:"created_on"`  // 创建时间
		ModifiedOn int64  `db:"modified_on"` // 修改时间
		DeletedOn  int64  `db:"deleted_on"`  // 删除时间
		IsDel      int64  `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPCommentContentModel(conn sqlx.SqlConn) *defaultPCommentContentModel {
	return &defaultPCommentContentModel{
		conn:  conn,
		table: "`p_comment_content`",
	}
}

func (m *defaultPCommentContentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPCommentContentModel) FindOne(ctx context.Context, id int64) (*PCommentContent, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pCommentContentRows, m.table)
	var resp PCommentContent
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPCommentContentModel) Insert(ctx context.Context, data *PCommentContent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pCommentContentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CommentId, data.UserId, data.Content, data.Type, data.Sort, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	return ret, err
}

func (m *defaultPCommentContentModel) Update(ctx context.Context, data *PCommentContent) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pCommentContentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CommentId, data.UserId, data.Content, data.Type, data.Sort, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	return err
}

func (m *defaultPCommentContentModel) tableName() string {
	return m.table
}
