// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pCommentReplyFieldNames          = builder.RawFieldNames(&PCommentReply{})
	pCommentReplyRows                = strings.Join(pCommentReplyFieldNames, ",")
	pCommentReplyRowsExpectAutoSet   = strings.Join(stringx.Remove(pCommentReplyFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	pCommentReplyRowsWithPlaceHolder = strings.Join(stringx.Remove(pCommentReplyFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cachePaopaoPCommentReplyIdPrefix = "cache:paopao:pCommentReply:id:"
)

type (
	pCommentReplyModel interface {
		Insert(ctx context.Context, data *PCommentReply) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PCommentReply, error)
		Update(ctx context.Context, data *PCommentReply) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPCommentReplyModel struct {
		sqlc.CachedConn
		table string
	}

	PCommentReply struct {
		Id         int64  `db:"id"`          // 回复ID
		CommentId  int64  `db:"comment_id"`  // 评论ID
		UserId     int64  `db:"user_id"`     // 用户ID
		AtUserId   int64  `db:"at_user_id"`  // @用户ID
		Content    string `db:"content"`     // 内容
		Ip         string `db:"ip"`          // IP地址
		IpLoc      string `db:"ip_loc"`      // IP城市地址
		CreatedOn  int64  `db:"created_on"`  // 创建时间
		ModifiedOn int64  `db:"modified_on"` // 修改时间
		DeletedOn  int64  `db:"deleted_on"`  // 删除时间
		IsDel      int64  `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPCommentReplyModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPCommentReplyModel {
	return &defaultPCommentReplyModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`p_comment_reply`",
	}
}

func (m *defaultPCommentReplyModel) Delete(ctx context.Context, id int64) error {
	paopaoPCommentReplyIdKey := fmt.Sprintf("%s%v", cachePaopaoPCommentReplyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, paopaoPCommentReplyIdKey)
	return err
}

func (m *defaultPCommentReplyModel) FindOne(ctx context.Context, id int64) (*PCommentReply, error) {
	paopaoPCommentReplyIdKey := fmt.Sprintf("%s%v", cachePaopaoPCommentReplyIdPrefix, id)
	var resp PCommentReply
	err := m.QueryRowCtx(ctx, &resp, paopaoPCommentReplyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pCommentReplyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPCommentReplyModel) Insert(ctx context.Context, data *PCommentReply) (sql.Result, error) {
	paopaoPCommentReplyIdKey := fmt.Sprintf("%s%v", cachePaopaoPCommentReplyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pCommentReplyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CommentId, data.UserId, data.AtUserId, data.Content, data.Ip, data.IpLoc, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	}, paopaoPCommentReplyIdKey)
	return ret, err
}

func (m *defaultPCommentReplyModel) Update(ctx context.Context, data *PCommentReply) error {
	paopaoPCommentReplyIdKey := fmt.Sprintf("%s%v", cachePaopaoPCommentReplyIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pCommentReplyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CommentId, data.UserId, data.AtUserId, data.Content, data.Ip, data.IpLoc, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	}, paopaoPCommentReplyIdKey)
	return err
}

func (m *defaultPCommentReplyModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePaopaoPCommentReplyIdPrefix, primary)
}

func (m *defaultPCommentReplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pCommentReplyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPCommentReplyModel) tableName() string {
	return m.table
}
