// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pCommentFieldNames          = builder.RawFieldNames(&PComment{})
	pCommentRows                = strings.Join(pCommentFieldNames, ",")
	pCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(pCommentFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	pCommentRowsWithPlaceHolder = strings.Join(stringx.Remove(pCommentFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	pCommentModel interface {
		Insert(ctx context.Context, data *PComment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PComment, error)
		Update(ctx context.Context, data *PComment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PComment struct {
		Id         int64  `db:"id"`          // 评论ID
		PostId     int64  `db:"post_id"`     // POST ID
		UserId     int64  `db:"user_id"`     // 用户ID
		Ip         string `db:"ip"`          // IP地址
		IpLoc      string `db:"ip_loc"`      // IP城市地址
		CreatedOn  int64  `db:"created_on"`  // 创建时间
		ModifiedOn int64  `db:"modified_on"` // 修改时间
		DeletedOn  int64  `db:"deleted_on"`  // 删除时间
		IsDel      int64  `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPCommentModel(conn sqlx.SqlConn) *defaultPCommentModel {
	return &defaultPCommentModel{
		conn:  conn,
		table: "`p_comment`",
	}
}

func (m *defaultPCommentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPCommentModel) FindOne(ctx context.Context, id int64) (*PComment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pCommentRows, m.table)
	var resp PComment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPCommentModel) Insert(ctx context.Context, data *PComment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, pCommentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.Ip, data.IpLoc, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	return ret, err
}

func (m *defaultPCommentModel) Update(ctx context.Context, data *PComment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pCommentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.Ip, data.IpLoc, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	return err
}

func (m *defaultPCommentModel) tableName() string {
	return m.table
}
