// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pPostAttachmentBillFieldNames          = builder.RawFieldNames(&PPostAttachmentBill{})
	pPostAttachmentBillRows                = strings.Join(pPostAttachmentBillFieldNames, ",")
	pPostAttachmentBillRowsExpectAutoSet   = strings.Join(stringx.Remove(pPostAttachmentBillFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	pPostAttachmentBillRowsWithPlaceHolder = strings.Join(stringx.Remove(pPostAttachmentBillFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cachePaopaoPPostAttachmentBillIdPrefix = "cache:paopao:pPostAttachmentBill:id:"
)

type (
	pPostAttachmentBillModel interface {
		Insert(ctx context.Context, data *PPostAttachmentBill) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PPostAttachmentBill, error)
		Update(ctx context.Context, data *PPostAttachmentBill) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPPostAttachmentBillModel struct {
		sqlc.CachedConn
		table string
	}

	PPostAttachmentBill struct {
		Id         int64 `db:"id"`          // 购买记录ID
		PostId     int64 `db:"post_id"`     // POST ID
		UserId     int64 `db:"user_id"`     // 用户ID
		PaidAmount int64 `db:"paid_amount"` // 支付金额
		CreatedOn  int64 `db:"created_on"`  // 创建时间
		ModifiedOn int64 `db:"modified_on"` // 修改时间
		DeletedOn  int64 `db:"deleted_on"`  // 删除时间
		IsDel      int64 `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPPostAttachmentBillModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPPostAttachmentBillModel {
	return &defaultPPostAttachmentBillModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`p_post_attachment_bill`",
	}
}

func (m *defaultPPostAttachmentBillModel) Delete(ctx context.Context, id int64) error {
	paopaoPPostAttachmentBillIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostAttachmentBillIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, paopaoPPostAttachmentBillIdKey)
	return err
}

func (m *defaultPPostAttachmentBillModel) FindOne(ctx context.Context, id int64) (*PPostAttachmentBill, error) {
	paopaoPPostAttachmentBillIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostAttachmentBillIdPrefix, id)
	var resp PPostAttachmentBill
	err := m.QueryRowCtx(ctx, &resp, paopaoPPostAttachmentBillIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostAttachmentBillRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPPostAttachmentBillModel) Insert(ctx context.Context, data *PPostAttachmentBill) (sql.Result, error) {
	paopaoPPostAttachmentBillIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostAttachmentBillIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, pPostAttachmentBillRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.PaidAmount, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	}, paopaoPPostAttachmentBillIdKey)
	return ret, err
}

func (m *defaultPPostAttachmentBillModel) Update(ctx context.Context, data *PPostAttachmentBill) error {
	paopaoPPostAttachmentBillIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostAttachmentBillIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pPostAttachmentBillRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.PaidAmount, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	}, paopaoPPostAttachmentBillIdKey)
	return err
}

func (m *defaultPPostAttachmentBillModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePaopaoPPostAttachmentBillIdPrefix, primary)
}

func (m *defaultPPostAttachmentBillModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostAttachmentBillRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPPostAttachmentBillModel) tableName() string {
	return m.table
}
