// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pPostCollectionFieldNames          = builder.RawFieldNames(&PPostCollection{})
	pPostCollectionRows                = strings.Join(pPostCollectionFieldNames, ",")
	pPostCollectionRowsExpectAutoSet   = strings.Join(stringx.Remove(pPostCollectionFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	pPostCollectionRowsWithPlaceHolder = strings.Join(stringx.Remove(pPostCollectionFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cachePaopaoPPostCollectionIdPrefix = "cache:paopao:pPostCollection:id:"
)

type (
	pPostCollectionModel interface {
		Insert(ctx context.Context, data *PPostCollection) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PPostCollection, error)
		Update(ctx context.Context, data *PPostCollection) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPPostCollectionModel struct {
		sqlc.CachedConn
		table string
	}

	PPostCollection struct {
		Id         int64 `db:"id"`          // 收藏ID
		PostId     int64 `db:"post_id"`     // POST ID
		UserId     int64 `db:"user_id"`     // 用户ID
		CreatedOn  int64 `db:"created_on"`  // 创建时间
		ModifiedOn int64 `db:"modified_on"` // 修改时间
		DeletedOn  int64 `db:"deleted_on"`  // 删除时间
		IsDel      int64 `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPPostCollectionModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPPostCollectionModel {
	return &defaultPPostCollectionModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`p_post_collection`",
	}
}

func (m *defaultPPostCollectionModel) Delete(ctx context.Context, id int64) error {
	paopaoPPostCollectionIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostCollectionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, paopaoPPostCollectionIdKey)
	return err
}

func (m *defaultPPostCollectionModel) FindOne(ctx context.Context, id int64) (*PPostCollection, error) {
	paopaoPPostCollectionIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostCollectionIdPrefix, id)
	var resp PPostCollection
	err := m.QueryRowCtx(ctx, &resp, paopaoPPostCollectionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostCollectionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPPostCollectionModel) Insert(ctx context.Context, data *PPostCollection) (sql.Result, error) {
	paopaoPPostCollectionIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostCollectionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, pPostCollectionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	}, paopaoPPostCollectionIdKey)
	return ret, err
}

func (m *defaultPPostCollectionModel) Update(ctx context.Context, data *PPostCollection) error {
	paopaoPPostCollectionIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostCollectionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pPostCollectionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	}, paopaoPPostCollectionIdKey)
	return err
}

func (m *defaultPPostCollectionModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePaopaoPPostCollectionIdPrefix, primary)
}

func (m *defaultPPostCollectionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostCollectionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPPostCollectionModel) tableName() string {
	return m.table
}
