// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pPostStarFieldNames          = builder.RawFieldNames(&PPostStar{})
	pPostStarRows                = strings.Join(pPostStarFieldNames, ",")
	pPostStarRowsExpectAutoSet   = strings.Join(stringx.Remove(pPostStarFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	pPostStarRowsWithPlaceHolder = strings.Join(stringx.Remove(pPostStarFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cachePaopaoPPostStarIdPrefix = "cache:paopao:pPostStar:id:"
)

type (
	pPostStarModel interface {
		Insert(ctx context.Context, data *PPostStar) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PPostStar, error)
		Update(ctx context.Context, data *PPostStar) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPPostStarModel struct {
		sqlc.CachedConn
		table string
	}

	PPostStar struct {
		Id         int64 `db:"id"`          // 收藏ID
		PostId     int64 `db:"post_id"`     // POST ID
		UserId     int64 `db:"user_id"`     // 用户ID
		CreatedOn  int64 `db:"created_on"`  // 创建时间
		ModifiedOn int64 `db:"modified_on"` // 修改时间
		DeletedOn  int64 `db:"deleted_on"`  // 删除时间
		IsDel      int64 `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPPostStarModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPPostStarModel {
	return &defaultPPostStarModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`p_post_star`",
	}
}

func (m *defaultPPostStarModel) Delete(ctx context.Context, id int64) error {
	paopaoPPostStarIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostStarIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, paopaoPPostStarIdKey)
	return err
}

func (m *defaultPPostStarModel) FindOne(ctx context.Context, id int64) (*PPostStar, error) {
	paopaoPPostStarIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostStarIdPrefix, id)
	var resp PPostStar
	err := m.QueryRowCtx(ctx, &resp, paopaoPPostStarIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostStarRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPPostStarModel) Insert(ctx context.Context, data *PPostStar) (sql.Result, error) {
	paopaoPPostStarIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostStarIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, pPostStarRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	}, paopaoPPostStarIdKey)
	return ret, err
}

func (m *defaultPPostStarModel) Update(ctx context.Context, data *PPostStar) error {
	paopaoPPostStarIdKey := fmt.Sprintf("%s%v", cachePaopaoPPostStarIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pPostStarRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	}, paopaoPPostStarIdKey)
	return err
}

func (m *defaultPPostStarModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePaopaoPPostStarIdPrefix, primary)
}

func (m *defaultPPostStarModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostStarRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPPostStarModel) tableName() string {
	return m.table
}
