// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pPostStarFieldNames          = builder.RawFieldNames(&PPostStar{})
	pPostStarRows                = strings.Join(pPostStarFieldNames, ",")
	pPostStarRowsExpectAutoSet   = strings.Join(stringx.Remove(pPostStarFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	pPostStarRowsWithPlaceHolder = strings.Join(stringx.Remove(pPostStarFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	pPostStarModel interface {
		Insert(ctx context.Context, data *PPostStar) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PPostStar, error)
		Update(ctx context.Context, data *PPostStar) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPPostStarModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PPostStar struct {
		Id         int64 `db:"id"`          // 收藏ID
		PostId     int64 `db:"post_id"`     // POST ID
		UserId     int64 `db:"user_id"`     // 用户ID
		CreatedOn  int64 `db:"created_on"`  // 创建时间
		ModifiedOn int64 `db:"modified_on"` // 修改时间
		DeletedOn  int64 `db:"deleted_on"`  // 删除时间
		IsDel      int64 `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPPostStarModel(conn sqlx.SqlConn) *defaultPPostStarModel {
	return &defaultPPostStarModel{
		conn:  conn,
		table: "`p_post_star`",
	}
}

func (m *defaultPPostStarModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPPostStarModel) FindOne(ctx context.Context, id int64) (*PPostStar, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pPostStarRows, m.table)
	var resp PPostStar
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPPostStarModel) Insert(ctx context.Context, data *PPostStar) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, pPostStarRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	return ret, err
}

func (m *defaultPPostStarModel) Update(ctx context.Context, data *PPostStar) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pPostStarRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PostId, data.UserId, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel, data.Id)
	return err
}

func (m *defaultPPostStarModel) tableName() string {
	return m.table
}
