// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pTagFieldNames          = builder.RawFieldNames(&PTag{})
	pTagRows                = strings.Join(pTagFieldNames, ",")
	pTagRowsExpectAutoSet   = strings.Join(stringx.Remove(pTagFieldNames, "`id`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), ",")
	pTagRowsWithPlaceHolder = strings.Join(stringx.Remove(pTagFieldNames, "`id`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), "=?,") + "=?"

	cachePaopaoPTagIdPrefix  = "cache:paopao:pTag:id:"
	cachePaopaoPTagTagPrefix = "cache:paopao:pTag:tag:"
)

type (
	pTagModel interface {
		Insert(ctx context.Context, data *PTag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PTag, error)
		FindOneByTag(ctx context.Context, tag string) (*PTag, error)
		Update(ctx context.Context, data *PTag) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPTagModel struct {
		sqlc.CachedConn
		table string
	}

	PTag struct {
		Id         int64  `db:"id"`          // 标签ID
		UserId     int64  `db:"user_id"`     // 创建者ID
		Tag        string `db:"tag"`         // 标签名
		QuoteNum   int64  `db:"quote_num"`   // 引用数
		CreatedOn  int64  `db:"created_on"`  // 创建时间
		ModifiedOn int64  `db:"modified_on"` // 修改时间
		DeletedOn  int64  `db:"deleted_on"`  // 删除时间
		IsDel      int64  `db:"is_del"`      // 是否删除 0 为未删除、1 为已删除
	}
)

func newPTagModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPTagModel {
	return &defaultPTagModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`p_tag`",
	}
}

func (m *defaultPTagModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	paopaoPTagIdKey := fmt.Sprintf("%s%v", cachePaopaoPTagIdPrefix, id)
	paopaoPTagTagKey := fmt.Sprintf("%s%v", cachePaopaoPTagTagPrefix, data.Tag)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, paopaoPTagIdKey, paopaoPTagTagKey)
	return err
}

func (m *defaultPTagModel) FindOne(ctx context.Context, id int64) (*PTag, error) {
	paopaoPTagIdKey := fmt.Sprintf("%s%v", cachePaopaoPTagIdPrefix, id)
	var resp PTag
	err := m.QueryRowCtx(ctx, &resp, paopaoPTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pTagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPTagModel) FindOneByTag(ctx context.Context, tag string) (*PTag, error) {
	paopaoPTagTagKey := fmt.Sprintf("%s%v", cachePaopaoPTagTagPrefix, tag)
	var resp PTag
	err := m.QueryRowIndexCtx(ctx, &resp, paopaoPTagTagKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `tag` = ? limit 1", pTagRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tag); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPTagModel) Insert(ctx context.Context, data *PTag) (sql.Result, error) {
	paopaoPTagIdKey := fmt.Sprintf("%s%v", cachePaopaoPTagIdPrefix, data.Id)
	paopaoPTagTagKey := fmt.Sprintf("%s%v", cachePaopaoPTagTagPrefix, data.Tag)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, pTagRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Tag, data.QuoteNum, data.CreatedOn, data.ModifiedOn, data.DeletedOn, data.IsDel)
	}, paopaoPTagIdKey, paopaoPTagTagKey)
	return ret, err
}

func (m *defaultPTagModel) Update(ctx context.Context, newData *PTag) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	paopaoPTagIdKey := fmt.Sprintf("%s%v", cachePaopaoPTagIdPrefix, data.Id)
	paopaoPTagTagKey := fmt.Sprintf("%s%v", cachePaopaoPTagTagPrefix, data.Tag)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pTagRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Tag, newData.QuoteNum, newData.CreatedOn, newData.ModifiedOn, newData.DeletedOn, newData.IsDel, newData.Id)
	}, paopaoPTagIdKey, paopaoPTagTagKey)
	return err
}

func (m *defaultPTagModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePaopaoPTagIdPrefix, primary)
}

func (m *defaultPTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pTagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPTagModel) tableName() string {
	return m.table
}
