// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/yiGmMk/zero-paopao/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/posts",
				Handler: GetPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tags",
				Handler: GetTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/auth/register",
				Handler: UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/auth/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/info",
				Handler: InfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
